remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Jakarta RESTful Web Services]
description: [Jakarta RESTful Web Services provides a specification document, TCK and foundational API to develop web services following the Representational State Transfer (REST) architectural pattern.]

links:
  source: https://github.com/QubitPi/jakartaee-rest
  javadocs: https://jakartaee-rest.qubitpi.org/apidocs
  docs: https://jakartaee-rest.qubitpi.org/jaxrs-spec.html
  download: https://github.com/jakartaee/rest/releases
  links:
    hide_issuetracker: true
  mailinglist: https://accounts.eclipse.org/mailing-list/jaxrs-dev
