
name: Jakarta REST CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17', '21' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B -ntp clean verify -Djaxrs.all.build
    - name: Build spec and apidocs
      run: mvn install
      working-directory: jaxrs-spec
    - name: Move Javadoc into documentation directory
      run: |        
        mv jaxrs-api/target/apidocs docs
        mv jaxrs-spec/target/generated-docs/spec.html docs/jaxrs-spec.html
        mv jaxrs-spec/target/generated-docs/spec.pdf docs/jaxrs-spec.pdf
    - name: Publish all docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        enable_jekyll: true
        user_name: QubitPi
        user_email: jack20220723@gmail.com
        cname: jakartaee-rest.qubitpi.org
